syntax = "proto3";

//do not change this properties
option java_package = "pl.edu.pwr.pwrinspace.poliwrocket.Model.MessageParser";
option java_outer_classname = "FrameProtos";

message LoRaFrame {
  optional uint32 tanwaState = 1;
  optional uint32 upTime = 2;
  optional int32 engineWorkingTime = 3;

  optional float pressureFuel = 4;
  optional float pressureN2 = 5;
  optional float pressureDroid = 6;
  optional float pressureOxi = 7;

  optional float pressureInjectorFuel = 8;
  optional float pressureInjectorOxi = 9;
  optional float pressureCombustionChamber = 10;

  optional bool statusFillN2O = 11;
  optional bool statusDeprN2O = 12;
  optional bool statusVentN2O = 13;
  optional bool statusArm = 14;
  optional bool igniterCont1 = 15;
  optional bool igniterCont2 = 16;

  optional float tanwaBattery = 17;

  optional float engineThrust = 18;
  optional float rocketWeight = 19;
  optional float tankWeight = 20;

  optional float tempInjector = 21;
  optional float tempCombustionChamber = 22;
  optional float tempExternalTank = 23;


  optional bool statusOxi = 24;
  optional bool statusFuel = 25;
  optional bool statusN2 = 26;
  optional bool statusQdN2O = 27;

  optional bool statusFillN2 = 28;
  optional bool statusDeprN2 = 29;
  optional bool statusQdN2 = 30;
  optional bool statusVentEth = 31;
  optional bool statusVentN2 = 32;

  optional float pressureCutoff = 33;

}

message LoRaSettings {
  optional int32 lora_freq_khz = 1;
  optional int32 lora_transmit_ms = 2;
  optional int32 countdown_time = 3;
  optional int32 ingition_time = 4;
  optional uint32 flash_enable = 5;
  optional uint32 buzzer_enable = 6;
}

message LoRaCommand {
  optional uint32 lora_dev_id = 1;
  optional uint32 sys_dev_id = 2;
  optional uint32 command = 3;
  optional int32 payload = 4;
}