syntax = "proto3";

//do not change this properties
option java_package = "pl.edu.pwr.pwrinspace.poliwrocket.Model.MessageParser";
option java_outer_classname = "FrameProtos";

message LoRaFrame {
   // --- MCB ---
  optional uint32 mcb_state = 1;
  optional uint32 uptime_ms = 2;                   // ms
  optional uint32 flight_time_ms = 3;               // ms
  optional uint32 mcb_batt = 4;
  optional float gps_lat = 5;
  optional float gps_long = 6;
  optional bool gps_sat_ok = 7;                    // >3 = OK
  optional sint32 altitude_m = 8;                   // meters
  optional sint32 velocity_m_s = 9;                 // m/s
  optional sint32 mcb_temperature = 10;
  optional float euler_fi = 11;
  optional float euler_psi = 12;
  optional float euler_theta = 13;

  // --- Recovery ---
  optional fixed32 recovery_flags = 14;

  // --- Pitot ---
  optional uint32 pitot_battery = 15;
  optional sint32 pitot_altitude = 16;
  optional sint32 pitot_velocity = 17;
  optional sint32 pitot_temperature = 18;

  // --- Valve states ---
  // bit0: OX_MAIN_STATE
  // bit1: N2_MAIN_STATE
  // bit2: OX_VENT_STATE
  // bit3: ETH_MAIN_STATE
  // bit4: ETH_VENT_STATE
  // bit5: N2_VENT_STATE
  optional fixed32 main_vent_flags = 19;

  // --- Byte data ---
  optional fixed32 n2_vent_bit_data_a = 20;

  optional fixed32 ox_vent_eth_main_bit_data_a = 21;
  optional fixed32 ox_vent_eth_main_bit_data_b = 22;
  optional fixed32 ox_vent_eth_main_bit_data_c = 23;

  optional fixed32 ox_main_bit_data_a = 24;
  optional fixed32 ox_main_bit_data_b = 25;

  optional fixed32 eth_vent_bit_data_a = 26;
  optional fixed32 eth_vent_bit_data_b = 27;

  // --- TANWA ---
  optional uint32 tanwa_battery = 28;
  optional uint32 tanwa_state = 29;

  // bit0: CAN_Weights_connection
  // bit1: CAN_Utility_connection
  // bit2: CAN_Sensor_connection
  // bit3: CAN_Power_connection
  // bit4: CAN_Solenoid_connection
  // bit5: igniter_1_continuity
  // bit6: igniter_2_continuity
  // bit7: soft_arm
  // bit8: abort_button
  // bit9: fill_N2O_state
  // bit10: depr_N2O_state
  // bit11: fill_N2_state
  // bit12: depr_N2_state
  // bit13: droid_N2O_state
  // bit14: droid_N2_state
  // bit15: heating_tank_state
  // bit16: heating_valves_state
  optional fixed32 tanwa_flags = 30;

  optional sint32 tanwa_thrust = 31;
  optional uint32 tanwa_tank_weight = 32;

  optional sint32 tanwa_temp_post_n2o_fill = 33;
  optional sint32 tanwa_temp_filling_wall = 34;
  optional uint32 tanwa_post_fill_n2o_pres = 35;
  optional uint32 tanwa_cutoff_n2o_pres = 36;
  optional uint32 tanwa_droid_n2o_pres = 37;
  optional uint32 tanwa_pre_reg_n2_pres = 38;
  optional uint32 tanwa_post_reg_n2_pres = 39;
  optional uint32 tanwa_post_fill_n2_pres = 40;
  optional uint32 tanwa_droid_n2_pres = 41;
  optional uint32 tanwa_comb_chamber_pres = 42;

  // --- Payload ---
  optional uint32 payload_battery = 43;

  // bit0: payload_connected
  // bit1: tanwa_connected
  // bit2: eth_vent_valve_connected
  // bit3: ox_main_connected
  // bit4: ox_vent_eth_main_connected
  // bit5: n2_vent_connected
  // bit6: pitot_connected
  optional fixed32 esp_now_connected_flags = 44;
  // bit0: payload_wkup
  // bit1: eth_vent_valve_wkup
  // bit2: ox_main_wkup
  // bit3: ox_vent_eth_main_wkup
  // bit4: n2_vent_wkup
  // bit5: pitot_wkup
  optional fixed32 esp_now_wkup_flags = 45;

  // --- Errors ---
  optional fixed32 errors = 46;
}

message LoRaFrameTanwa {
  optional uint32 tanwaState = 1;
  optional uint32 upTime = 2;
  optional int32 engineWorkingTime = 3;

  optional float pressureFuel = 4;
  optional float pressureN2 = 5;
  optional float pressureDroid = 6;
  optional float pressureOxi = 7;

  optional float pressureInjectorFuel = 8;
  optional float pressureInjectorOxi = 9;
  optional float pressureCombustionChamber = 10;

  optional bool statusFillN2O = 11;
  optional bool statusDeprN2O = 12;
  optional bool statusVentN2O = 13;
  optional bool statusArm = 14;
  optional bool igniterCont1 = 15;
  optional bool igniterCont2 = 16;

  optional float tanwaBattery = 17;

  optional float engineThrust = 18;
  optional float rocketWeight = 19;
  optional float tankWeight = 20;

  optional float tempInjector = 21;
  optional float tempCombustionChamber = 22;
  optional float tempExternalTank = 23;


  optional bool statusOxi = 24;
  optional bool statusFuel = 25;
  optional bool statusN2 = 26;
  optional bool statusQdN2O = 27;

  optional bool statusFillN2 = 28;
  optional bool statusDeprN2 = 29;
  optional bool statusQdN2 = 30;
  optional bool statusVentEth = 31;
  optional bool statusVentN2 = 32;

  optional float pressureCutoff = 33;
}

message LoRaSettings {
  optional int32 lora_freq_khz = 1;
  optional int32 lora_transmit_ms = 2;
  optional int32 countdown_time = 3;
  optional int32 ingition_time = 4;
  optional uint32 flash_enable = 5;
  optional uint32 buzzer_enable = 6;
}

message LoRaCommand {
  optional uint32 lora_dev_id = 1;
  optional uint32 sys_dev_id = 2;
  optional uint32 command = 3;
  optional int32 payload = 4;
}