package pl.edu.pwr.pwrinspace.poliwrocket.Controller;

public enum ControllerNameEnum {
    MAIN_CONTROLLER,
    MAP_CONTROLLER,
    POWER_CONTROLLER,
    VALVES_CONTROLLER,
    DATA_CONTROLLER,
    MORE_DATA_CONTROLLER,
    ABORT_CONTROLLER,
    STATES_CONTROLLER,
    START_CONTROL_CONTROLLER,
    CONNECTION_CONTROLLER,

}
